[tool.poetry]
name = "dfa"
version = "0.3.0"
description = "Python library for modeling DFAs."
authors = ["Marcell Vazquez-Chanlatte <marcell.vc@eecs.berkeley.edu>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"
attrs = "^19.1"
funcy = "^1.12"

[tool.poetry.dev-dependencies]
hypothesis = "^4.24"
parsimonious = "^0.8.1"
pytest = "^4.6"
pytest-cov = "^2.7"
pytest-flake8 = "^1.0"
pytest-sugar = "^0.9.2"
pytest-xdist = "^1.28"
codecov = "^2.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
