[tool.poetry]
name = "dfa"
readme="README.md"
version = "1.0.4"
description = "Python library for modeling DFAs, Moore Machines, and Transition Systems."
authors = ["Marcell Vazquez-Chanlatte <marcell.vc@eecs.berkeley.edu>"]
repository = "https://github.com/mvcisback/dfa"
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
attrs = "^19.1"
funcy = "^1.12"
lazytree = "^0.3.1"
pydot = {version = "^1.4", optional = true}

[tool.poetry.dev-dependencies]
hypothesis = "^4.24"
parsimonious = "^0.8.1"
pydot = "^1.4"
pytest = "^4.6"
pytest-cov = "^2.7"
pytest-flake8 = "^1.0"
pytest-sugar = "^0.9.2"
pytest-xdist = "^1.28"
codecov = "^2.0"

[tool.poetry.extras]
draw = ["pydot"]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
